# SPDX-License-Identifier: MIT
# F1 interface for the CU pod (Core + CU cluster). The DU reaches the CU on 10.0.0.120 (F1-C SCTP 38472, F1-U UDP 2152).
# Attach with pod annotation: k8s.v1.cni.cncf.io/networks: oai-f1
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: oai-f1
  namespace: oai
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eno1",
      "mode": "bridge",
      "ipam": {"type": "static", "addresses": [{"address": "10.0.0.120/24"}]}
    }
